export enum ContentType {
  Note = 'Note',
  ItemsKey = 'SN|ItemsKey',
  Component = 'SN|Component',
  Editor = 'SN|Editor',
  ExtensionRepo = 'SN|ExtensionRepo',
  ServerExtension = 'SF|Extension',
  MFA = 'SF|MFA',
  Unknown = 'Unknown',
  Extension = 'Extension',
  FileSafeCredentials = 'SN|FileSafe|Credentials',
  FileSafeFile = 'SN|FileSafe|File',
  FileSafeFileMetadata = 'SN|FileSafe|FileMetadata',
  FileSafeIntegration = 'SN|FileSafe|Integration',
  Privileges = 'SN|Privileges',
  SmartTag = 'SN|SmartTag',
  Theme = 'SN|Theme',
  UserPreferences = 'SN|UserPreferences',
  Tag = 'Tag',
}
